name: Publish

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

permissions:
  id-token: write

env:
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true

jobs:
  publish-npm:
    name: 'Publish: npm Registry'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: "https://registry.npmjs.org"

      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: bun install

      - name: Build code
        run: bun run build

      - name: Test
        run: bun run test

      - name: Test
        run: bun run test:cf

      - name: 'Publish'
        run: |
          NODE_AUTH_TOKEN="" npm publish --provenance --access=public
